title: Mundo Animal C
tagline:
logo:
description: >-
baseurl: /homolog8/vcsabia-c/mundo-animal-c
url: http://leadmedia.com.br
lang: pt-br
theme: minima
author:
  - name: Lucas Sales
    url: http://github.com/LucasBortolini
plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript
sass:
  sourcemap: never
postcss:
  cache: false
collections:
  pages:
    output: true